# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Build a new app using local key"
  lane :buildApp do
    gradle(
      task: "assemble",
      build_type: "Release"
    )
  end

  desc "Deploy a beta version to the Google Play"
  lane :deployBetaToPlaystore do
    # gradle(task: 'assemble', build_type: 'Release')
    upload_to_play_store(
        track: "beta",
        aab: "../build/app/outputs/bundle/release/app-release.aab",
        skip_upload_apk: true,
        skip_upload_metadata: true,
        skip_upload_images: true,
        skip_upload_screenshots: true,
        release_status: "draft",
        version_code: flutter_version()["version_code"]
      )
  end
  
  desc "Deploy a internal version to the Google Play"
  lane :deployInternalToPlaystore do
    # gradle(task: 'assemble', build_type: 'Release')
    upload_to_play_store(
        track: "internal",
        aab: "../build/app/outputs/bundle/release/app-release.aab",
        skip_upload_apk: true,
        skip_upload_metadata: true,
        skip_upload_images: true,
        skip_upload_screenshots: true,
        release_status: "draft",
        version_code: flutter_version()["version_code"]
      )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean bundleRelease", release_status: "draft")
    upload_to_play_store(release_status: "draft" )
  end
end
