# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Build a new app using local key"
  lane :buildApp do
    gradle(
      task: 'assemble',
      build_type: 'Release'
    )
  end

  desc "Deploy a beta version to the Google Play"
  lane :beta do
    gradle(task: 'clean bundleRelease')
    upload_to_play_store(track: 'beta', release_status: 'draft', aab: '../build/app/outputs/bundle/release/app-release.aab', json_key_data: ENV['PLAY_CONFIG_JSON'])
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: 'clean bundleRelease', release_status: 'draft')
    upload_to_play_store(release_status: 'draft' )
  end
end
