name: Playstore deployment
on:
  push:
    branches:
      - main

jobs:
  #CI
  build_android:
    name: Building Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 12.x

      - name: Decrypt Android keys
        run: sh ./.github/scripts/decrypt_android_secrets.sh
        env:
          ANDROID_KEYS_ZIP_PASSPHRASE: ${{ secrets.ANDROID_KEYS_ZIP_PASSPHRASE }}

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"
          flutter-version: 3.10.4

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Build the appbundle
        run: flutter build appbundle --no-tree-shake-icons --release

      - name: Upload artifact to Github
        uses: actions/upload-artifact@v1
        with:
          name: app-release
          path: build/app/outputs/bundle/release/app-release.aab
  #CD
  deploy_android:
    name: Deploying to playstore
    runs-on: ubuntu-latest
    needs: [build_android]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 12.x

      - name: Decrypt Android keys
        run: sh ./.github/scripts/decrypt_android_secrets.sh
        env:
          ANDROID_KEYS_ZIP_PASSPHRASE: ${{ secrets.ANDROID_KEYS_ZIP_PASSPHRASE }}

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"
          flutter-version: 3.10.4

      - name: Upload artifact to Github
        uses: actions/upload-artifact@v1
        with:
          name: app-release
          path: build/app/outputs/bundle/release/app-release.aab

      - name: Run Fastlane
        uses: maierj/fastlane-action@v1.4.0
        with:
          lane: beta
          subdirectory: android
